### ISSUE TITLE
Having trouble with /proc/acpi/nuc_led creation

### ISSUE THREAD

**Issue by Nebarik** [milesp20/intel_nuc_led#14]
Not sure if this is a issue so much as i might just be doing something stupid.

Running Ubuntu 16.04, Linux 4.15.0-24-generic kernal on a Nuc NUC7i7BNB, BIOS Version: BNKBL357.86A.0065.2018.0606.1639 (aka version 65, the latest). LEDs are set to SW control in BIOS. 

I go through the install steps via deb. it makes the deb file fine, i install it fine. But there's no /proc/acpi/nuc_led file. Not sure if there's a unspoken step here I'm missing. 

I also tried making and installing it in various other ways but I'm super clueless here so any help would be appreciated.

**Comment by Nebarik** [comment]
Ended up working it out. as suspected im just a idiot. For anyone else having trouble what i did was:

- installed via dkms command:
"make dkms-install"

- actually paid attention to the output and found a .ko file in the folder mentioned:
"Installing to /lib/modules/4.15.0-24-generic/updates/dkms/"

- copied it over to my folder then ran:
"sudo modprobe wmi"
"sudo insmod nuc_led.ko" 

- it worked!

**Comment by tmsteen** [comment]
Ran into this same issue and the fix worked but doesn't manually loading the kernel module with `insmod` defeat the purpose of using DKMS?

Admittedly, I have very little knowledge of how kernel modules work.

**Comment by Nebarik** [comment]
I know even less about kernal modules and DKMS. 

Since doing the above. I've reinstalled my server from scratch, and the same thing happens. Every reboot i have to redo "insmod" to reload the nuc_led.ko file..

What's interesting as well is every now and then i have to remake it in DKMS because the module number has changed (?). old one wont insmod and the new one gets made into a new folder (where the * is) "/lib/modules/4.15.0-*-generic/updates/dkms"

**Comment by rytilahti** [comment]
The whole point of dkms is that the module gets automatically recompiled when the kernel gets updated, the number you see changing is the kernel release. Typing `dkms status` should list the active dkms modules (like `intel-nuc-led, 1.0, 4.19.0-1-amd64, x86_64: installed`), one of which should be for your active kernel version (as shown by `uname -r`). Using `modprobe nuc_led` should then work automatically.

**Comment by tmsteen** [comment]
So `make dkms-install` seems to work and persist across reboots while `make dkms-deb` following by the `dpkg` install of that package does not. 

From my perspective, that solves this but should be more clear in the README as the preferred method as it is less work all around.
