### ISSUE TITLE
Fade settings not working

### ISSUE THREAD

**Issue by lstein** [milesp20/intel_nuc_led#6]
Attempting to set to fade_slow or fade_medium fails with a "Unable to set NUC LED state: invalid parameter" error. Example:

`echo 'ring,100,fade_slow,red' > /proc/acpi/nuc_led`

**Comment by milesp20** [comment]
What model of NUC are you using, and what BIOS version do you currently have installed?  You can check your BIOS version / BIOS release date with dmidecode - should be first page near the top.
